# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17NlNYmo6ZBOtdt1hFLdMKhIcC5fjcolE
"""

import pandas as pd
import numpy as np
data = pd.read_csv("/content/seeds_dataset.txt", names = ['Area', 'perimeter', 'compactness', 'length of kernel', 'width of kernel', 'asymmetry coefficient','length of kernel group', 'variety of wheat'], sep='\t')
data=data.dropna()
data.head()
# data.info()

# import matplotlib.pyplot as plt
# import seaborn as sb
# plt.figure(figsize=(20,15))
# print(data.corr())
# dataplot = sb.heatmap(data.corr(), cmap="YlGnBu", annot=True)
# plt.show()

from pandas.plotting import scatter_matrix
attributes = ['Area', 'perimeter', 'compactness', 'variety of wheat']
scatter_matrix(data[attributes], figsize=(20,15))
data.plot(kind='scatter', x='Area', y='variety of wheat', alpha=0.7)

data["variety of wheat"].value_counts()

labels = np.array(data["variety of wheat"])
data = np.array(data)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import precision_score
from sklearn.metrics import mean_squared_error
train_data, test_data, train_labels, test_labels = train_test_split(data, labels, test_size = 0.2, random_state=42, stratify=None)
print('Training Features Shape:', train_data.shape)
print('Training Labels Shape:', train_labels.shape)
print('Testing Features Shape:', test_data.shape)
print('Testing Labels Shape:', test_labels.shape)
model = LinearRegression()
model.fit(train_data, train_labels)
y = model.predict(test_data)

print("The Mean Squared Error Value is: ", mean_squared_error(test_labels, y))
print("Weights: ", model.coef_)
print("Intercepts: ", model.intercept_)
model.score(test_data, y)
train_labels = train_labels.astype(np.int64)
test_labels = test_labels.astype(np.int64)
a = cross_val_score(model, train_data, train_labels)
print(a)
print(a.mean())